[workspace]
members = ["projects/*"]
default-members = [
    "projects/rainbow-core",
    "projects/rainbow-pest",
    "projects/rainbow-render",
    "projects/syntect-rainbow",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
