[package]
name = "rainbow-render"
version = "0.1.0"
authors = ["Aster <galaster@foxmail.com>"]
description = "Arc Readable Configuration"
license = "MPL-2.0"
readme = "../../Readme.md"
repository = "https://github.com/doki-land/arc-rs"
exclude = ["/tests/*"]
edition = "2018"

[dependencies]
html_parser = "0.6.3"
rainbow-core = { version = "0.1.0", path = "../rainbow-core" }

[features]
default = []
serde = []
lsp = []
